### ISSUE TITLE
Refuses to boot (again)

### ISSUE THREAD

**Issue by darkst0rm223** [XDuskAshes/dawn#17]
![javaw_hdMsyZn0sM](https://github.com/XDuskAshes/dawn/assets/107277121/9ceb9fc3-855e-4530-ba8a-6ba6d9cd0259)

**Comment by TheAio** [comment]
Thanks for the report and not giving up on us. For the sake of organization i think it is easier to keep this thread in issue #16 which i have reopened.

I'm closing this as duplicate.
