### ISSUE TITLE
Rewrite startup

### ISSUE THREAD

**Issue by TheAio** [XDuskAshes/dawn#19]
For the sake of keeping track of thoughts and ideas im opening a issue here based on something @XDuskAshes wrote in discord.

> Startup keeps resetting the computer label and I wanna change that but I forget which part does it
I'm probably gonna rewrite startup entirely atp

Should we do this or not? It will cause more work, but it does give the opportunity to improve the file.
Im assigning @XDuskAshes to this just because ze mentioned it, but i might help out if i can later :)

**Comment by XDuskAshes** [comment]
> Im assigning @XDuskAshes to this just because ze mentioned it, but i might help out if i can later :)
(Insert 'touched by being referred to correctly' noise)
Also yeah, It's gonna be more efficient when it's rewritten

**Comment by TheAio** [comment]
Well of course i will refer to you correctly :) Doing otherwise would not be respectful.
I just hope that rewriting it wont set us back too much time wise.
