### ISSUE TITLE
Change install to allow installing from idev and release

### ISSUE THREAD

**Issue by XDuskAshes** [XDuskAshes/dawn#21]
Self explanatory

**Comment by TheAio** [comment]
Nit: `Self explanatory` is not a very good description even if it is true. Also lets try and set labels to keep things organized.

**Comment by XDuskAshes** [comment]
> Nit: `Self explanatory` is not a very good description even if it is true. Also lets try and set labels to keep things organized.

Github mobile hates labeling for some reason.

**Comment by TheAio** [comment]
oh yeah. That's true, one of the things i really do not like with GitHub mobile.

**Comment by XDuskAshes** [comment]
This was done a damn while ago
